name: TestBuild

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Echo build number
      run: echo ${{github.run_number}}

    - name: Run build script
      run: mvn clean install

    - name: Set Version
      run: export VERSION="1.0.${{ github.run_number }}"

    - name: Tag and Push
      run: |
        git config user.email "nikos@petalidis.gr"
        git config user.name "Nikos Petalidis"
        git tag $VERSION
        git push origin $VERSION

    - name: Build docker 2
      run: |
        docker build -t ghcr.io/npetalid/app:1.0.${{ github.run_number }} .
        docker push ghcr.io/npetalid/app:1.0.${{ github.run_number }}
