name: Production Build

on:
  release:
    types: [published, deleted]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch latest release
      id: fetch-latest-release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        exclude_types: draft|prerelease
        github_token: ${{ github.token }}

    - name: Print values
      id: print-latest-release
      run: |
        echo ${{ steps.nodejs.etch-latest-release.tag_name }}
        echo "${{ github.ref_name }}"


#    - name: Build docker
#      run: |
#        echo ${{ github.ref_name }}
#        docker tag ghcr.io/npetalid/app:latest ghcr.io/npetalid/app-prod:latest
#        docker push ghcr.io/npetalid/app-prod:latest

