name: Production Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}


    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build docker
      run: |
        echo ${{ github.ref_name }}
        docker tag ghcr.io/npetalid/app:latest ghcr.io/npetalid/app-prod:latest
        docker push ghcr.io/npetalid/app-prod:latest

