name: Production Build

on:
  release:
    types: [published, deleted]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest Github release
      run: |
        response=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/releases/latest)

        # Check if the curl request was successful (HTTP status code 2xx)
        if [ $? -eq 0 ]; then
            echo $response
          # Use jq to extract the tag_name from the JSON response
            echo "TAG=$(echo "$response" | jq -r '.[0].tag_name')" >> $GITHUB_ENV
        else
          exit -1
        fi
    - name: Print values
      id: print-latest-release
      run: |
        echo ${{ env.TAG }}
        echo "${{ github.ref_name }}"


#    - name: Build docker
#      run: |
#        echo ${{ github.ref_name }}
#        docker tag ghcr.io/npetalid/app:latest ghcr.io/npetalid/app-prod:latest
#        docker push ghcr.io/npetalid/app-prod:latest

