name: TestBuild

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run build script
      run: mvn clean install
