name: Production Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set version
      run: |
        echo "VERSION=$(echo "${{ github.ref_name }}" | cut -d'-' -f2)" >> $GITHUB_ENV

    - name: Build docker
      run: |
        echo ${{ github.ref_name }}
        echo ${{ env.VERSION }}
        docker build -t ghcr.io/npetalid/app:${{ env.VERSION }}  ghcr.io/npetalid/app:latest
        docker push ghcr.io/npetalid/app:${{ env.VERSION }}
        docker push ghcr.io/npetalid/app:latest


