name: Production Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest Github release
      run: |
        echo ${{ github.event_name }}
        echo ${{ github.event_type }}

    - name: Print values
      id: print-latest-release
      run: |
        echo ${{ env.TAG }}
        echo "${{ github.ref_name }}"


#    - name: Build docker
#      run: |
#        echo ${{ github.ref_name }}
#        docker tag ghcr.io/npetalid/app:latest ghcr.io/npetalid/app-prod:latest
#        docker push ghcr.io/npetalid/app-prod:latest

